# Site settings
author: Tiara Matthews
title: 
header-img: img/home-bg.png
email: tiaramatthews96@yahoo.com
copyright_name: Tiara Matthews
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  tiaramatthews1

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
